// GENERATED from the Fastly builtin signature list — do not edit by hand.
// Regenerate with tmp/gen-builtin-types.py when new builtins appear.

export interface BuiltinSignature {
	args: string[][];
	ret: string | null;
}

export const BUILTIN_SIGNATURES: Record<string, BuiltinSignature> = {
	"accept.charset_lookup": { args: [["STRING", "STRING", "STRING"]], ret: "STRING" },
	"accept.encoding_lookup": { args: [["STRING", "STRING", "STRING"]], ret: "STRING" },
	"accept.language_filter_basic": {
		args: [["STRING", "STRING", "STRING", "INTEGER"]],
		ret: "STRING",
	},
	"accept.language_lookup": { args: [["STRING", "STRING", "STRING"]], ret: "STRING" },
	"accept.media_lookup": { args: [["STRING", "STRING", "STRING", "STRING"]], ret: "STRING" },
	"addr.extract_bits": { args: [["IP", "INTEGER", "INTEGER"]], ret: "INTEGER" },
	"addr.is_ipv4": { args: [["IP"]], ret: "BOOL" },
	"addr.is_ipv6": { args: [["IP"]], ret: "BOOL" },
	"bin.base64_to_hex": { args: [["STRING"]], ret: "STRING" },
	"bin.hex_to_base64": { args: [["STRING"]], ret: "STRING" },
	"boltsort.sort": { args: [["STRING"]], ret: "STRING" },
	"crypto.decrypt_base64": {
		args: [["ID", "ID", "ID", "STRING", "STRING", "STRING"]],
		ret: "STRING",
	},
	"crypto.decrypt_hex": { args: [["ID", "ID", "ID", "STRING", "STRING", "STRING"]], ret: "STRING" },
	"crypto.encrypt_base64": {
		args: [["ID", "ID", "ID", "STRING", "STRING", "STRING"]],
		ret: "STRING",
	},
	"crypto.encrypt_hex": { args: [["ID", "ID", "ID", "STRING", "STRING", "STRING"]], ret: "STRING" },
	cstr_escape: { args: [["STRING"]], ret: "STRING" },
	"digest.awsv4_hmac": {
		args: [["STRING", "STRING", "STRING", "STRING", "STRING"]],
		ret: "STRING",
	},
	"digest.base64": { args: [["STRING"]], ret: "STRING" },
	"digest.base64_decode": { args: [["STRING"]], ret: "STRING" },
	"digest.base64url": { args: [["STRING"]], ret: "STRING" },
	"digest.base64url_decode": { args: [["STRING"]], ret: "STRING" },
	"digest.base64url_nopad": { args: [["STRING"]], ret: "STRING" },
	"digest.base64url_nopad_decode": { args: [["STRING"]], ret: "STRING" },
	"digest.ecdsa_verify": {
		args: [
			["ID", "STRING", "STRING", "STRING", "ID"],
			["ID", "STRING", "STRING", "STRING", "ID", "ID"],
		],
		ret: "BOOL",
	},
	"digest.hash_crc32": { args: [["STRING"]], ret: "STRING" },
	"digest.hash_crc32b": { args: [["STRING"]], ret: "STRING" },
	"digest.hash_md5": { args: [["STRING"]], ret: "STRING" },
	"digest.hash_sha1": { args: [["STRING"]], ret: "STRING" },
	"digest.hash_sha1_from_base64": { args: [["STRING"]], ret: "STRING" },
	"digest.hash_sha224": { args: [["STRING"]], ret: "STRING" },
	"digest.hash_sha256": { args: [["STRING"]], ret: "STRING" },
	"digest.hash_sha256_from_base64": { args: [["STRING"]], ret: "STRING" },
	"digest.hash_sha384": { args: [["STRING"]], ret: "STRING" },
	"digest.hash_sha512": { args: [["STRING"]], ret: "STRING" },
	"digest.hash_sha512_from_base64": { args: [["STRING"]], ret: "STRING" },
	"digest.hash_xxh32": { args: [["STRING"]], ret: "STRING" },
	"digest.hash_xxh32_from_base64": { args: [["STRING"]], ret: "STRING" },
	"digest.hash_xxh64": { args: [["STRING"]], ret: "STRING" },
	"digest.hash_xxh64_from_base64": { args: [["STRING"]], ret: "STRING" },
	"digest.hmac_md5": { args: [["STRING", "STRING"]], ret: "STRING" },
	"digest.hmac_md5_base64": { args: [["STRING", "STRING"]], ret: "STRING" },
	"digest.hmac_sha1": { args: [["STRING", "STRING"]], ret: "STRING" },
	"digest.hmac_sha1_base64": { args: [["STRING", "STRING"]], ret: "STRING" },
	"digest.hmac_sha256": { args: [["STRING", "STRING"]], ret: "STRING" },
	"digest.hmac_sha256_base64": { args: [["STRING", "STRING"]], ret: "STRING" },
	"digest.hmac_sha256_with_base64_key": { args: [["STRING", "STRING"]], ret: "STRING" },
	"digest.hmac_sha512": { args: [["STRING", "STRING"]], ret: "STRING" },
	"digest.hmac_sha512_base64": { args: [["STRING", "STRING"]], ret: "STRING" },
	"digest.rsa_verify": {
		args: [
			["ID", "STRING", "STRING", "STRING", "ID"],
			["ID", "STRING", "STRING", "STRING"],
		],
		ret: "BOOL",
	},
	"digest.secure_is_equal": { args: [["STRING", "STRING"]], ret: "BOOL" },
	"digest.time_hmac_md5": { args: [["STRING", "INTEGER", "INTEGER"]], ret: "STRING" },
	"digest.time_hmac_sha1": { args: [["STRING", "INTEGER", "INTEGER"]], ret: "STRING" },
	"digest.time_hmac_sha256": { args: [["STRING", "INTEGER", "INTEGER"]], ret: "STRING" },
	"digest.time_hmac_sha512": { args: [["STRING", "INTEGER", "INTEGER"]], ret: "STRING" },
	early_hints: { args: [["STRING", "STRING_LIST"]], ret: null },
	"fastly.ff.last_hop_was_serviceid": { args: [["STRING"]], ret: "BOOL" },
	"fastly.hash": { args: [["STRING", "INTEGER", "INTEGER", "INTEGER"]], ret: "INTEGER" },
	"fastly.try_select_shield": { args: [["BACKEND", "BACKEND"]], ret: "BACKEND" },
	"h2.disable_header_compression": { args: [["STRING_LIST"]], ret: null },
	"h2.push": { args: [["STRING"], ["STRING", "STRING"]], ret: null },
	"h3.alt_svc": { args: [], ret: null },
	"header.filter": { args: [["ID", "STRING_LIST"]], ret: null },
	"header.filter_except": { args: [["ID", "STRING_LIST"]], ret: null },
	"header.get": { args: [["ID", "STRING"]], ret: "STRING" },
	"header.set": { args: [["ID", "STRING", "STRING"]], ret: null },
	"header.unset": { args: [["ID", "STRING"]], ret: null },
	http_status_matches: { args: [["INTEGER", "STRING"]], ret: "BOOL" },
	"json.escape": { args: [["STRING"]], ret: "STRING" },
	"math.acos": { args: [["FLOAT"]], ret: "FLOAT" },
	"math.acosh": { args: [["FLOAT"]], ret: "FLOAT" },
	"math.asin": { args: [["FLOAT"]], ret: "FLOAT" },
	"math.asinh": { args: [["FLOAT"]], ret: "FLOAT" },
	"math.atan": { args: [["FLOAT"]], ret: "FLOAT" },
	"math.atan2": { args: [["FLOAT", "FLOAT"]], ret: "FLOAT" },
	"math.atanh": { args: [["FLOAT"]], ret: "FLOAT" },
	"math.ceil": { args: [["FLOAT"]], ret: "FLOAT" },
	"math.cos": { args: [["FLOAT"]], ret: "FLOAT" },
	"math.cosh": { args: [["FLOAT"]], ret: "FLOAT" },
	"math.exp": { args: [["FLOAT"]], ret: "FLOAT" },
	"math.exp2": { args: [["FLOAT"]], ret: "FLOAT" },
	"math.floor": { args: [["FLOAT"]], ret: "FLOAT" },
	"math.is_finite": { args: [["FLOAT"]], ret: "BOOL" },
	"math.is_infinite": { args: [["FLOAT"]], ret: "BOOL" },
	"math.is_nan": { args: [["FLOAT"]], ret: "BOOL" },
	"math.is_normal": { args: [["FLOAT"]], ret: "BOOL" },
	"math.is_subnormal": { args: [["FLOAT"]], ret: "BOOL" },
	"math.log": { args: [["FLOAT"]], ret: "FLOAT" },
	"math.log10": { args: [["FLOAT"]], ret: "FLOAT" },
	"math.log2": { args: [["FLOAT"]], ret: "FLOAT" },
	"math.round": { args: [["FLOAT"]], ret: "FLOAT" },
	"math.roundeven": { args: [["FLOAT"]], ret: "FLOAT" },
	"math.roundhalfdown": { args: [["FLOAT"]], ret: "FLOAT" },
	"math.roundhalfup": { args: [["FLOAT"]], ret: "FLOAT" },
	"math.sin": { args: [["FLOAT"]], ret: "FLOAT" },
	"math.sinh": { args: [["FLOAT"]], ret: "FLOAT" },
	"math.sqrt": { args: [["FLOAT"]], ret: "FLOAT" },
	"math.tan": { args: [["FLOAT"]], ret: "FLOAT" },
	"math.tanh": { args: [["FLOAT"]], ret: "FLOAT" },
	"math.trunc": { args: [["FLOAT"]], ret: "FLOAT" },
	parse_time_delta: { args: [["STRING"]], ret: "INTEGER" },
	"querystring.add": { args: [["STRING", "STRING", "STRING"]], ret: "STRING" },
	"querystring.clean": { args: [["STRING"]], ret: "STRING" },
	"querystring.filter": { args: [["STRING", "STRING"]], ret: "STRING" },
	"querystring.filter_except": { args: [["STRING", "STRING"]], ret: "STRING" },
	"querystring.filtersep": { args: [], ret: "STRING" },
	"querystring.get": { args: [["STRING", "STRING"]], ret: "STRING" },
	"querystring.globfilter": { args: [["STRING", "STRING"]], ret: "STRING" },
	"querystring.globfilter_except": { args: [["STRING", "STRING"]], ret: "STRING" },
	"querystring.regfilter": { args: [["STRING", "STRING"]], ret: "STRING" },
	"querystring.regfilter_except": { args: [["STRING", "STRING"]], ret: "STRING" },
	"querystring.remove": { args: [["STRING"]], ret: "STRING" },
	"querystring.set": { args: [["STRING", "STRING", "STRING"]], ret: "STRING" },
	"querystring.sort": { args: [["STRING"]], ret: "STRING" },
	randombool: { args: [["INTEGER", "INTEGER"]], ret: "BOOL" },
	randombool_seeded: { args: [["INTEGER", "INTEGER", "INTEGER"]], ret: "BOOL" },
	randomint: { args: [["INTEGER", "INTEGER"]], ret: "INTEGER" },
	randomint_seeded: { args: [["INTEGER", "INTEGER", "INTEGER"]], ret: "INTEGER" },
	randomstr: { args: [["INTEGER"], ["INTEGER", "STRING"]], ret: "STRING" },
	"ratelimit.check_rate": {
		args: [["STRING", "ID", "INTEGER", "INTEGER", "INTEGER", "ID", "RTIME"]],
		ret: "BOOL",
	},
	"ratelimit.check_rates": {
		args: [
			[
				"STRING",
				"ID",
				"INTEGER",
				"INTEGER",
				"INTEGER",
				"ID",
				"INTEGER",
				"INTEGER",
				"INTEGER",
				"ID",
				"RTIME",
			],
		],
		ret: "BOOL",
	},
	"ratelimit.penaltybox_add": { args: [["ID", "STRING", "RTIME"]], ret: null },
	"ratelimit.penaltybox_has": { args: [["ID", "STRING"]], ret: "BOOL" },
	"ratelimit.ratecounter_increment": { args: [["ID", "STRING", "INTEGER"]], ret: "INTEGER" },
	regsub: { args: [["STRING", "STRING", "STRING"]], ret: "STRING" },
	regsuball: { args: [["STRING", "STRING", "STRING"]], ret: "STRING" },
	"resp.tarpit": { args: [["INTEGER", "INTEGER"], ["INTEGER"]], ret: null },
	"setcookie.delete_by_name": { args: [["ID", "STRING"]], ret: "BOOL" },
	"setcookie.get_value_by_name": { args: [["ID", "STRING"]], ret: "STRING" },
	"std.anystr2ip": { args: [["STRING", "STRING"]], ret: "IP" },
	"std.atof": { args: [["STRING"]], ret: "FLOAT" },
	"std.atoi": { args: [["STRING"]], ret: "INTEGER" },
	"std.basename": { args: [["STRING"]], ret: "STRING" },
	"std.collect": { args: [["ID"], ["ID", "STRING"]], ret: null },
	"std.count": { args: [["ID"]], ret: "INTEGER" },
	"std.dirname": { args: [["STRING"]], ret: "STRING" },
	"std.integer2time": { args: [["INTEGER"]], ret: "TIME" },
	"std.ip": { args: [["STRING", "STRING"]], ret: "IP" },
	"std.ip2str": { args: [["IP"]], ret: "STRING" },
	"std.itoa": { args: [["INTEGER", "INTEGER"], ["INTEGER"]], ret: "STRING" },
	"std.itoa_charset": { args: [["INTEGER", "STRING"]], ret: "STRING" },
	"std.prefixof": { args: [["STRING", "STRING"]], ret: "BOOL" },
	"std.replace": { args: [["STRING", "STRING", "STRING"]], ret: "STRING" },
	"std.replace_prefix": { args: [["STRING", "STRING", "STRING"]], ret: "STRING" },
	"std.replace_suffix": { args: [["STRING", "STRING", "STRING"]], ret: "STRING" },
	"std.replaceall": { args: [["STRING", "STRING", "STRING"]], ret: "STRING" },
	"std.str2ip": { args: [["STRING", "STRING"]], ret: "IP" },
	"std.strcasecmp": { args: [["STRING", "STRING"]], ret: "BOOL" },
	"std.strlen": { args: [["STRING"]], ret: "INTEGER" },
	"std.strpad": { args: [["STRING", "INTEGER", "STRING"]], ret: "STRING" },
	"std.strrep": { args: [["STRING", "INTEGER"]], ret: "STRING" },
	"std.strrev": { args: [["STRING"]], ret: "STRING" },
	"std.strstr": { args: [["STRING", "STRING"]], ret: "STRING" },
	"std.strtof": { args: [["STRING", "INTEGER"]], ret: "FLOAT" },
	"std.strtol": { args: [["STRING", "INTEGER"]], ret: "INTEGER" },
	"std.suffixof": { args: [["STRING", "STRING"]], ret: "BOOL" },
	"std.time": { args: [["STRING", "TIME"]], ret: "TIME" },
	"std.tolower": { args: [["STRING"]], ret: "STRING" },
	"std.toupper": { args: [["STRING"]], ret: "STRING" },
	strftime: { args: [["STRING", "TIME"]], ret: "STRING" },
	subfield: {
		args: [
			["STRING", "STRING", "STRING"],
			["STRING", "STRING"],
		],
		ret: "STRING",
	},
	substr: {
		args: [
			["STRING", "INTEGER", "INTEGER"],
			["STRING", "INTEGER"],
		],
		ret: "STRING",
	},
	"table.contains": { args: [["TABLE", "STRING"]], ret: "BOOL" },
	"table.lookup": {
		args: [
			["TABLE", "STRING", "STRING"],
			["TABLE", "STRING"],
		],
		ret: "STRING",
	},
	"table.lookup_acl": { args: [["TABLE", "STRING", "ACL"]], ret: "ACL" },
	"table.lookup_backend": { args: [["TABLE", "STRING", "BACKEND"]], ret: "BACKEND" },
	"table.lookup_bool": { args: [["TABLE", "STRING", "BOOL"]], ret: "BOOL" },
	"table.lookup_float": { args: [["TABLE", "STRING", "FLOAT"]], ret: "FLOAT" },
	"table.lookup_integer": { args: [["TABLE", "STRING", "INTEGER"]], ret: "INTEGER" },
	"table.lookup_ip": { args: [["TABLE", "STRING", "IP"]], ret: "IP" },
	"table.lookup_regex": { args: [["TABLE", "STRING"]], ret: "REGEX" },
	"table.lookup_rtime": { args: [["TABLE", "STRING", "RTIME"]], ret: "RTIME" },
	"time.add": { args: [["TIME", "RTIME"]], ret: "TIME" },
	"time.hex_to_time": { args: [["INTEGER", "STRING"]], ret: "TIME" },
	"time.interval_elapsed_ratio": { args: [["TIME", "TIME", "TIME"]], ret: "FLOAT" },
	"time.is_after": { args: [["TIME", "TIME"]], ret: "BOOL" },
	"time.runits": { args: [["STRING", "RTIME"]], ret: "STRING" },
	"time.sub": { args: [["TIME", "RTIME"]], ret: "TIME" },
	"time.units": { args: [["STRING", "TIME"]], ret: "STRING" },
	"url.normalize": { args: [["STRING"]], ret: "STRING" },
	urldecode: { args: [["STRING"]], ret: "STRING" },
	urlencode: { args: [["STRING"]], ret: "STRING" },
	"utf8.codepoint_count": { args: [["STRING"]], ret: "INTEGER" },
	"utf8.is_valid": { args: [["STRING"]], ret: "BOOL" },
	"utf8.strpad": { args: [["STRING", "INTEGER", "STRING"]], ret: "STRING" },
	"utf8.substr": {
		args: [
			["STRING", "INTEGER", "INTEGER"],
			["STRING", "INTEGER"],
		],
		ret: "STRING",
	},
	"uuid.dns": { args: [], ret: "STRING" },
	"uuid.is_valid": { args: [["STRING"]], ret: "BOOL" },
	"uuid.is_version3": { args: [["STRING"]], ret: "BOOL" },
	"uuid.is_version4": { args: [["STRING"]], ret: "BOOL" },
	"uuid.is_version5": { args: [["STRING"]], ret: "BOOL" },
	"uuid.is_version7": { args: [["STRING"]], ret: "BOOL" },
	"uuid.oid": { args: [], ret: "STRING" },
	"uuid.url": { args: [], ret: "STRING" },
	"uuid.version3": { args: [["STRING", "STRING"]], ret: "STRING" },
	"uuid.version4": { args: [], ret: "STRING" },
	"uuid.version5": { args: [["STRING", "STRING"]], ret: "STRING" },
	"uuid.version7": { args: [], ret: "STRING" },
	"uuid.x500": { args: [], ret: "STRING" },
	xml_escape: { args: [["STRING"]], ret: "STRING" },
};

export interface VariableSignature {
	get: string | null;
	set: string | null;
}

export const VARIABLE_TYPES: Record<string, VariableSignature> = {
	"backend.conn.is_tls": { get: "BOOL", set: null },
	"backend.conn.tls_protocol": { get: "STRING", set: null },
	"backend.socket.congestion_algorithm": { get: "STRING", set: null },
	"backend.socket.cwnd": { get: "INTEGER", set: null },
	"backend.socket.tcpi_advmss": { get: "INTEGER", set: null },
	"backend.socket.tcpi_bytes_acked": { get: "INTEGER", set: null },
	"backend.socket.tcpi_bytes_received": { get: "INTEGER", set: null },
	"backend.socket.tcpi_data_segs_in": { get: "INTEGER", set: null },
	"backend.socket.tcpi_data_segs_out": { get: "INTEGER", set: null },
	"backend.socket.tcpi_delivery_rate": { get: "INTEGER", set: null },
	"backend.socket.tcpi_delta_retrans": { get: "INTEGER", set: null },
	"backend.socket.tcpi_last_data_sent": { get: "INTEGER", set: null },
	"backend.socket.tcpi_max_pacing_rate": { get: "INTEGER", set: null },
	"backend.socket.tcpi_min_rtt": { get: "INTEGER", set: null },
	"backend.socket.tcpi_notsent_bytes": { get: "INTEGER", set: null },
	"backend.socket.tcpi_pacing_rate": { get: "INTEGER", set: null },
	"backend.socket.tcpi_pmtu": { get: "INTEGER", set: null },
	"backend.socket.tcpi_rcv_mss": { get: "INTEGER", set: null },
	"backend.socket.tcpi_rcv_rtt": { get: "INTEGER", set: null },
	"backend.socket.tcpi_rcv_space": { get: "INTEGER", set: null },
	"backend.socket.tcpi_rcv_ssthresh": { get: "INTEGER", set: null },
	"backend.socket.tcpi_reordering": { get: "INTEGER", set: null },
	"backend.socket.tcpi_rtt": { get: "INTEGER", set: null },
	"backend.socket.tcpi_rttvar": { get: "INTEGER", set: null },
	"backend.socket.tcpi_segs_in": { get: "INTEGER", set: null },
	"backend.socket.tcpi_segs_out": { get: "INTEGER", set: null },
	"backend.socket.tcpi_snd_cwnd": { get: "INTEGER", set: null },
	"backend.socket.tcpi_snd_mss": { get: "INTEGER", set: null },
	"backend.socket.tcpi_snd_ssthresh": { get: "INTEGER", set: null },
	"backend.socket.tcpi_total_retrans": { get: "INTEGER", set: null },
	"bereq.between_bytes_timeout": { get: "RTIME", set: "RTIME" },
	"bereq.body_bytes_written": { get: "INTEGER", set: null },
	"bereq.bytes_written": { get: "INTEGER", set: null },
	"bereq.connect_timeout": { get: "RTIME", set: "RTIME" },
	"bereq.fetch_timeout": { get: "RTIME", set: "RTIME" },
	"bereq.first_byte_timeout": { get: "RTIME", set: "RTIME" },
	"bereq.header_bytes_written": { get: "INTEGER", set: null },
	"bereq.headers": { get: "ID", set: null },
	"bereq.is_clustering": { get: "BOOL", set: null },
	"bereq.max_reuse_idle_time": { get: "RTIME", set: "RTIME" },
	"bereq.method": { get: "STRING", set: "STRING" },
	"bereq.proto": { get: "STRING", set: null },
	"bereq.request": { get: "STRING", set: "STRING" },
	"bereq.url": { get: "STRING", set: "STRING" },
	"bereq.url.basename": { get: "STRING", set: null },
	"bereq.url.dirname": { get: "STRING", set: null },
	"bereq.url.ext": { get: "STRING", set: null },
	"bereq.url.path": { get: "STRING", set: null },
	"bereq.url.qs": { get: "STRING", set: null },
	"beresp.backend.alternate_ips": { get: "STRING", set: null },
	"beresp.backend.ip": { get: "IP", set: null },
	"beresp.backend.name": { get: "STRING", set: null },
	"beresp.backend.port": { get: "INTEGER", set: null },
	"beresp.backend.requests": { get: "INTEGER", set: null },
	"beresp.backend.src_ip": { get: "IP", set: null },
	"beresp.backend.src_port": { get: "INTEGER", set: null },
	"beresp.brotli": { get: "BOOL", set: "BOOL" },
	"beresp.cacheable": { get: "BOOL", set: "BOOL" },
	"beresp.do_esi": { get: "BOOL", set: "BOOL" },
	"beresp.do_stream": { get: "BOOL", set: "BOOL" },
	"beresp.grace": { get: "RTIME", set: "RTIME" },
	"beresp.gzip": { get: "BOOL", set: "BOOL" },
	"beresp.handshake_time_to_origin_ms": { get: "INTEGER", set: null },
	"beresp.headers": { get: "ID", set: null },
	"beresp.hipaa": { get: "BOOL", set: "BOOL" },
	"beresp.pci": { get: "BOOL", set: "BOOL" },
	"beresp.proto": { get: "STRING", set: null },
	"beresp.response": { get: "STRING", set: "STRING" },
	"beresp.saintmode": { get: null, set: "RTIME" },
	"beresp.stale_if_error": { get: "RTIME", set: "RTIME" },
	"beresp.stale_while_revalidate": { get: "RTIME", set: "RTIME" },
	"beresp.status": { get: "INTEGER", set: "INTEGER" },
	"beresp.ttl": { get: "RTIME", set: "RTIME" },
	"beresp.used_alternate_path_to_origin": { get: "BOOL", set: null },
	"client.as.name": { get: "STRING", set: null },
	"client.as.number": { get: "INTEGER", set: null },
	"client.bot.name": { get: "STRING", set: null },
	"client.browser.name": { get: "STRING", set: null },
	"client.browser.version": { get: "STRING", set: null },
	"client.class.bot": { get: "BOOL", set: null },
	"client.class.browser": { get: "BOOL", set: null },
	"client.class.checker": { get: "BOOL", set: null },
	"client.class.downloader": { get: "BOOL", set: null },
	"client.class.feedreader": { get: "BOOL", set: null },
	"client.class.filter": { get: "BOOL", set: null },
	"client.class.masquerading": { get: "BOOL", set: null },
	"client.class.spam": { get: "BOOL", set: null },
	"client.display.height": { get: "INTEGER", set: null },
	"client.display.ppi": { get: "INTEGER", set: null },
	"client.display.touchscreen": { get: "BOOL", set: null },
	"client.display.width": { get: "INTEGER", set: null },
	"client.geo.area_code": { get: "INTEGER", set: null },
	"client.geo.city": { get: "STRING", set: null },
	"client.geo.city.ascii": { get: "STRING", set: null },
	"client.geo.city.latin1": { get: "STRING", set: null },
	"client.geo.city.utf8": { get: "STRING", set: null },
	"client.geo.conn_speed": { get: "STRING", set: null },
	"client.geo.conn_type": { get: "STRING", set: null },
	"client.geo.continent_code": { get: "STRING", set: null },
	"client.geo.country_code": { get: "STRING", set: null },
	"client.geo.country_code3": { get: "STRING", set: null },
	"client.geo.country_name": { get: "STRING", set: null },
	"client.geo.country_name.ascii": { get: "STRING", set: null },
	"client.geo.country_name.latin1": { get: "STRING", set: null },
	"client.geo.country_name.utf8": { get: "STRING", set: null },
	"client.geo.gmt_offset": { get: "INTEGER", set: null },
	"client.geo.ip_override": { get: "STRING", set: "STRING" },
	"client.geo.latitude": { get: "FLOAT", set: null },
	"client.geo.longitude": { get: "FLOAT", set: null },
	"client.geo.metro_code": { get: "INTEGER", set: null },
	"client.geo.postal_code": { get: "STRING", set: null },
	"client.geo.proxy_description": { get: "STRING", set: null },
	"client.geo.proxy_type": { get: "STRING", set: null },
	"client.geo.region": { get: "STRING", set: null },
	"client.geo.region.ascii": { get: "STRING", set: null },
	"client.geo.region.latin1": { get: "STRING", set: null },
	"client.geo.region.utf8": { get: "STRING", set: null },
	"client.geo.utc_offset": { get: "INTEGER", set: null },
	"client.identified": { get: "INTEGER", set: null },
	"client.identity": { get: "STRING", set: "STRING" },
	"client.ip": { get: "STRING", set: null },
	"client.os.name": { get: "STRING", set: null },
	"client.os.version": { get: "STRING", set: null },
	"client.platform.ereader": { get: "BOOL", set: null },
	"client.platform.gameconsole": { get: "BOOL", set: null },
	"client.platform.hwtype": { get: "STRING", set: null },
	"client.platform.mediaplayer": { get: "BOOL", set: null },
	"client.platform.mobile": { get: "BOOL", set: null },
	"client.platform.model": { get: "STRING", set: null },
	"client.platform.smarttv": { get: "BOOL", set: null },
	"client.platform.tablet": { get: "BOOL", set: null },
	"client.platform.tvplayer": { get: "BOOL", set: null },
	"client.platform.vendor": { get: "STRING", set: null },
	"client.port": { get: "INTEGER", set: null },
	"client.requests": { get: "INTEGER", set: null },
	"client.sess_timeout": { get: "RTIME", set: "RTIME" },
	"client.socket.congestion_algorithm": { get: "STRING", set: "STRING" },
	"client.socket.cwnd": { get: "INTEGER", set: "INTEGER" },
	"client.socket.nexthop": { get: "IP", set: null },
	"client.socket.pace": { get: "INTEGER", set: "INTEGER" },
	"client.socket.ploss": { get: "FLOAT", set: null },
	"client.socket.tcp_info": { get: "BOOL", set: null },
	"client.socket.tcpi_advmss": { get: "INTEGER", set: null },
	"client.socket.tcpi_bytes_acked": { get: "INTEGER", set: null },
	"client.socket.tcpi_bytes_received": { get: "INTEGER", set: null },
	"client.socket.tcpi_data_segs_in": { get: "INTEGER", set: null },
	"client.socket.tcpi_data_segs_out": { get: "INTEGER", set: null },
	"client.socket.tcpi_delivery_rate": { get: "INTEGER", set: null },
	"client.socket.tcpi_delta_retrans": { get: "INTEGER", set: null },
	"client.socket.tcpi_last_data_sent": { get: "INTEGER", set: null },
	"client.socket.tcpi_max_pacing_rate": { get: "INTEGER", set: null },
	"client.socket.tcpi_min_rtt": { get: "INTEGER", set: null },
	"client.socket.tcpi_notsent_bytes": { get: "INTEGER", set: null },
	"client.socket.tcpi_pacing_rate": { get: "INTEGER", set: null },
	"client.socket.tcpi_pmtu": { get: "INTEGER", set: null },
	"client.socket.tcpi_rcv_mss": { get: "INTEGER", set: null },
	"client.socket.tcpi_rcv_rtt": { get: "INTEGER", set: null },
	"client.socket.tcpi_rcv_space": { get: "INTEGER", set: null },
	"client.socket.tcpi_rcv_ssthresh": { get: "INTEGER", set: null },
	"client.socket.tcpi_reordering": { get: "INTEGER", set: null },
	"client.socket.tcpi_rtt": { get: "INTEGER", set: null },
	"client.socket.tcpi_rttvar": { get: "INTEGER", set: null },
	"client.socket.tcpi_segs_in": { get: "INTEGER", set: null },
	"client.socket.tcpi_segs_out": { get: "INTEGER", set: null },
	"client.socket.tcpi_snd_cwnd": { get: "INTEGER", set: null },
	"client.socket.tcpi_snd_mss": { get: "INTEGER", set: null },
	"client.socket.tcpi_snd_ssthresh": { get: "INTEGER", set: null },
	"client.socket.tcpi_total_retrans": { get: "INTEGER", set: null },
	"esi.allow_inside_cdata": { get: "BOOL", set: "BOOL" },
	"fastly.bot.analyzed": { get: "BOOL", set: null },
	"fastly.bot.category": { get: "STRING", set: null },
	"fastly.bot.category.is_accessibility": { get: "BOOL", set: null },
	"fastly.bot.category.is_ai_crawler": { get: "BOOL", set: null },
	"fastly.bot.category.is_ai_fetcher": { get: "BOOL", set: null },
	"fastly.bot.category.is_content_fetcher": { get: "BOOL", set: null },
	"fastly.bot.category.is_headless": { get: "BOOL", set: null },
	"fastly.bot.category.is_monitoring_and_site_tools": { get: "BOOL", set: null },
	"fastly.bot.category.is_online_marketing": { get: "BOOL", set: null },
	"fastly.bot.category.is_page_preview": { get: "BOOL", set: null },
	"fastly.bot.category.is_platform_integrations": { get: "BOOL", set: null },
	"fastly.bot.category.is_research": { get: "BOOL", set: null },
	"fastly.bot.category.is_search_engine_crawler": { get: "BOOL", set: null },
	"fastly.bot.category.is_search_engine_optimization": { get: "BOOL", set: null },
	"fastly.bot.category.is_security_tools": { get: "BOOL", set: null },
	"fastly.bot.category.is_verified": { get: "BOOL", set: null },
	"fastly.bot.detected": { get: "BOOL", set: null },
	"fastly.bot.name": { get: "STRING", set: null },
	"fastly.ddos_detected": { get: "BOOL", set: null },
	"fastly.error": { get: "STRING", set: null },
	"fastly.ff.visits_this_pop": { get: "INTEGER", set: null },
	"fastly.ff.visits_this_pop_this_service": { get: "INTEGER", set: null },
	"fastly.ff.visits_this_service": { get: "INTEGER", set: null },
	"fastly.is_staging": { get: "BOOL", set: null },
	"fastly_info.edge.is_tls": { get: "BOOL", set: null },
	"fastly_info.h2.fingerprint": { get: "STRING", set: null },
	"fastly_info.h2.is_push": { get: "BOOL", set: null },
	"fastly_info.h2.stream_id": { get: "INTEGER", set: null },
	"fastly_info.host_header": { get: "STRING", set: null },
	"fastly_info.is_cluster_edge": { get: "BOOL", set: null },
	"fastly_info.is_cluster_shield": { get: "BOOL", set: null },
	"fastly_info.is_h2": { get: "BOOL", set: null },
	"fastly_info.is_h3": { get: "BOOL", set: null },
	"fastly_info.oh_fingerprint": { get: "STRING", set: null },
	"fastly_info.request_id": { get: "STRING", set: null },
	"fastly_info.state": { get: "STRING", set: null },
	"fastly_info.version": { get: "STRING", set: null },
	"geoip.area_code": { get: "INTEGER", set: null },
	"geoip.city": { get: "STRING", set: null },
	"geoip.city.ascii": { get: "STRING", set: null },
	"geoip.city.latin1": { get: "STRING", set: null },
	"geoip.city.utf8": { get: "STRING", set: null },
	"geoip.continent_code": { get: "STRING", set: null },
	"geoip.country_code": { get: "STRING", set: null },
	"geoip.country_code3": { get: "STRING", set: null },
	"geoip.country_name": { get: "STRING", set: null },
	"geoip.country_name.ascii": { get: "STRING", set: null },
	"geoip.country_name.latin1": { get: "STRING", set: null },
	"geoip.country_name.utf8": { get: "STRING", set: null },
	"geoip.ip_override": { get: "STRING", set: "STRING" },
	"geoip.latitude": { get: "FLOAT", set: null },
	"geoip.longitude": { get: "FLOAT", set: null },
	"geoip.metro_code": { get: "INTEGER", set: null },
	"geoip.postal_code": { get: "STRING", set: null },
	"geoip.region": { get: "STRING", set: null },
	"geoip.region.ascii": { get: "STRING", set: null },
	"geoip.region.latin1": { get: "STRING", set: null },
	"geoip.region.utf8": { get: "STRING", set: null },
	"geoip.use_x_forwarded_for": { get: "BOOL", set: "BOOL" },
	"math.1_PI": { get: "FLOAT", set: null },
	"math.2PI": { get: "FLOAT", set: null },
	"math.2_PI": { get: "FLOAT", set: null },
	"math.2_SQRTPI": { get: "FLOAT", set: null },
	"math.E": { get: "FLOAT", set: null },
	"math.FLOAT_DIG": { get: "INTEGER", set: null },
	"math.FLOAT_EPSILON": { get: "FLOAT", set: null },
	"math.FLOAT_MANT_DIG": { get: "INTEGER", set: null },
	"math.FLOAT_MAX": { get: "FLOAT", set: null },
	"math.FLOAT_MAX_10_EXP": { get: "INTEGER", set: null },
	"math.FLOAT_MAX_EXP": { get: "INTEGER", set: null },
	"math.FLOAT_MIN": { get: "FLOAT", set: null },
	"math.FLOAT_MIN_10_EXP": { get: "INTEGER", set: null },
	"math.FLOAT_MIN_EXP": { get: "INTEGER", set: null },
	"math.FLOAT_RADIX": { get: "INTEGER", set: null },
	"math.INTEGER_BIT": { get: "INTEGER", set: null },
	"math.INTEGER_MAX": { get: "INTEGER", set: null },
	"math.INTEGER_MIN": { get: "INTEGER", set: null },
	"math.LN10": { get: "FLOAT", set: null },
	"math.LN2": { get: "FLOAT", set: null },
	"math.LOG10E": { get: "FLOAT", set: null },
	"math.LOG2E": { get: "FLOAT", set: null },
	"math.NAN": { get: "FLOAT", set: null },
	"math.NEG_HUGE_VAL": { get: "FLOAT", set: null },
	"math.NEG_INFINITY": { get: "FLOAT", set: null },
	"math.PHI": { get: "FLOAT", set: null },
	"math.PI": { get: "FLOAT", set: null },
	"math.PI_2": { get: "FLOAT", set: null },
	"math.PI_4": { get: "FLOAT", set: null },
	"math.POS_HUGE_VAL": { get: "FLOAT", set: null },
	"math.POS_INFINITY": { get: "FLOAT", set: null },
	"math.SQRT1_2": { get: "FLOAT", set: null },
	"math.SQRT2": { get: "FLOAT", set: null },
	"math.TAU": { get: "FLOAT", set: null },
	now: { get: "TIME", set: null },
	"now.sec": { get: "STRING", set: null },
	"obj.age": { get: "RTIME", set: null },
	"obj.cacheable": { get: "BOOL", set: null },
	"obj.entered": { get: "RTIME", set: null },
	"obj.grace": { get: "RTIME", set: "RTIME" },
	"obj.headers": { get: "ID", set: null },
	"obj.hits": { get: "INTEGER", set: null },
	"obj.is_hipaa": { get: "BOOL", set: null },
	"obj.is_pci": { get: "BOOL", set: null },
	"obj.lastuse": { get: "RTIME", set: null },
	"obj.proto": { get: "STRING", set: null },
	"obj.response": { get: "STRING", set: "STRING" },
	"obj.stale_if_error": { get: "RTIME", set: null },
	"obj.stale_while_revalidate": { get: "RTIME", set: null },
	"obj.status": { get: "INTEGER", set: "INTEGER" },
	"obj.ttl": { get: "RTIME", set: "RTIME" },
	"quic.cc.cwnd": { get: "INTEGER", set: null },
	"quic.cc.ssthresh": { get: "INTEGER", set: null },
	"quic.num_bytes.received": { get: "INTEGER", set: null },
	"quic.num_bytes.sent": { get: "INTEGER", set: null },
	"quic.num_packets.ack_received": { get: "INTEGER", set: null },
	"quic.num_packets.decryption_failed": { get: "INTEGER", set: null },
	"quic.num_packets.late_acked": { get: "INTEGER", set: null },
	"quic.num_packets.lost": { get: "INTEGER", set: null },
	"quic.num_packets.received": { get: "INTEGER", set: null },
	"quic.num_packets.sent": { get: "INTEGER", set: null },
	"quic.rtt.latest": { get: "INTEGER", set: null },
	"quic.rtt.minimum": { get: "INTEGER", set: null },
	"quic.rtt.smoothed": { get: "INTEGER", set: null },
	"quic.rtt.variance": { get: "INTEGER", set: null },
	"req.backend": { get: "REQBACKEND", set: "REQBACKEND" },
	"req.backend.healthy": { get: "BOOL", set: null },
	"req.backend.ip": { get: "IP", set: null },
	"req.backend.is_cluster": { get: "BOOL", set: null },
	"req.backend.is_origin": { get: "BOOL", set: null },
	"req.backend.is_shield": { get: "BOOL", set: null },
	"req.backend.name": { get: "STRING", set: null },
	"req.backend.port": { get: "INTEGER", set: null },
	"req.body": { get: "STRING", set: null },
	"req.body.base64": { get: "STRING", set: null },
	"req.body_bytes_read": { get: "INTEGER", set: null },
	"req.bytes_read": { get: "INTEGER", set: null },
	"req.customer_id": { get: "STRING", set: null },
	"req.digest": { get: "STRING", set: null },
	"req.digest.ratio": { get: "FLOAT", set: null },
	"req.enable_range_on_pass": { get: "BOOL", set: "BOOL" },
	"req.enable_segmented_caching": { get: "BOOL", set: "BOOL" },
	"req.esi": { get: "BOOL", set: "BOOL" },
	"req.esi_level": { get: "INTEGER", set: null },
	"req.grace": { get: "RTIME", set: "RTIME" },
	"req.hash": { get: "STRING", set: "STRING" },
	"req.hash_always_miss": { get: "BOOL", set: "BOOL" },
	"req.hash_ignore_busy": { get: "BOOL", set: "BOOL" },
	"req.header_bytes_read": { get: "INTEGER", set: null },
	"req.headers": { get: "ID", set: null },
	"req.is_background_fetch": { get: "BOOL", set: null },
	"req.is_clustering": { get: "BOOL", set: null },
	"req.is_esi_subreq": { get: "BOOL", set: null },
	"req.is_ipv6": { get: "BOOL", set: null },
	"req.is_purge": { get: "BOOL", set: null },
	"req.is_ssl": { get: "BOOL", set: null },
	"req.max_stale_if_error": { get: "RTIME", set: "RTIME" },
	"req.max_stale_while_revalidate": { get: "RTIME", set: "RTIME" },
	"req.method": { get: "STRING", set: "STRING" },
	"req.postbody": { get: "STRING", set: null },
	"req.proto": { get: "STRING", set: null },
	"req.protocol": { get: "STRING", set: null },
	"req.request": { get: "STRING", set: "STRING" },
	"req.restarts": { get: "INTEGER", set: null },
	"req.service_id": { get: "STRING", set: null },
	"req.topurl": { get: "STRING", set: null },
	"req.url": { get: "STRING", set: "STRING" },
	"req.url.basename": { get: "STRING", set: null },
	"req.url.dirname": { get: "STRING", set: null },
	"req.url.ext": { get: "STRING", set: null },
	"req.url.path": { get: "STRING", set: null },
	"req.url.qs": { get: "STRING", set: null },
	"req.vcl": { get: "STRING", set: null },
	"req.vcl.generation": { get: "INTEGER", set: null },
	"req.vcl.md5": { get: "STRING", set: null },
	"req.vcl.version": { get: "INTEGER", set: null },
	"req.xid": { get: "STRING", set: null },
	"resp.body_bytes_written": { get: "INTEGER", set: null },
	"resp.bytes_written": { get: "INTEGER", set: null },
	"resp.completed": { get: "BOOL", set: null },
	"resp.header_bytes_written": { get: "INTEGER", set: null },
	"resp.headers": { get: "ID", set: null },
	"resp.is_locally_generated": { get: "BOOL", set: null },
	"resp.proto": { get: "STRING", set: null },
	"resp.response": { get: "STRING", set: "STRING" },
	"resp.stale": { get: "BOOL", set: "BOOL" },
	"resp.stale.is_error": { get: "BOOL", set: "BOOL" },
	"resp.stale.is_revalidating": { get: "BOOL", set: "BOOL" },
	"resp.status": { get: "INTEGER", set: "INTEGER" },
	"segmented_caching.autopurged": { get: "BOOL", set: null },
	"segmented_caching.block_number": { get: "INTEGER", set: null },
	"segmented_caching.block_size": { get: "INTEGER", set: "INTEGER" },
	"segmented_caching.cancelled": { get: "BOOL", set: null },
	"segmented_caching.client_req.is_open_ended": { get: "BOOL", set: null },
	"segmented_caching.client_req.is_range": { get: "BOOL", set: null },
	"segmented_caching.client_req.range_high": { get: "INTEGER", set: null },
	"segmented_caching.client_req.range_low": { get: "INTEGER", set: null },
	"segmented_caching.completed": { get: "BOOL", set: null },
	"segmented_caching.error": { get: "STRING", set: null },
	"segmented_caching.failed": { get: "BOOL", set: null },
	"segmented_caching.is_inner_req": { get: "BOOL", set: null },
	"segmented_caching.is_outer_req": { get: "BOOL", set: null },
	"segmented_caching.obj.complete_length": { get: "INTEGER", set: null },
	"segmented_caching.rounded_req.range_high": { get: "INTEGER", set: null },
	"segmented_caching.rounded_req.range_low": { get: "INTEGER", set: null },
	"segmented_caching.total_blocks": { get: "INTEGER", set: null },
	"server.billing_region": { get: "STRING", set: null },
	"server.datacenter": { get: "STRING", set: null },
	"server.hostname": { get: "STRING", set: null },
	"server.identity": { get: "STRING", set: null },
	"server.ip": { get: "IP", set: null },
	"server.pop": { get: "STRING", set: null },
	"server.port": { get: "INTEGER", set: null },
	"server.region": { get: "STRING", set: null },
	"stale.exists": { get: "STRING", set: null },
	"time.elapsed": { get: "RTIME", set: null },
	"time.elapsed.msec": { get: "STRING", set: null },
	"time.elapsed.msec_frac": { get: "STRING", set: null },
	"time.elapsed.sec": { get: "STRING", set: null },
	"time.elapsed.usec": { get: "STRING", set: null },
	"time.elapsed.usec_frac": { get: "STRING", set: null },
	"time.end": { get: "TIME", set: null },
	"time.end.msec": { get: "STRING", set: null },
	"time.end.msec_frac": { get: "STRING", set: null },
	"time.end.sec": { get: "STRING", set: null },
	"time.end.usec": { get: "STRING", set: null },
	"time.end.usec_frac": { get: "STRING", set: null },
	"time.start": { get: "TIME", set: null },
	"time.start.msec": { get: "STRING", set: null },
	"time.start.msec_frac": { get: "STRING", set: null },
	"time.start.sec": { get: "STRING", set: null },
	"time.start.usec": { get: "STRING", set: null },
	"time.start.usec_frac": { get: "STRING", set: null },
	"time.to_first_byte": { get: "RTIME", set: null },
	"tls.client.certificate.dn": { get: "STRING", set: null },
	"tls.client.certificate.is_cert_bad": { get: "BOOL", set: null },
	"tls.client.certificate.is_cert_expired": { get: "BOOL", set: null },
	"tls.client.certificate.is_cert_missing": { get: "BOOL", set: null },
	"tls.client.certificate.is_cert_revoked": { get: "BOOL", set: null },
	"tls.client.certificate.is_cert_unknown": { get: "BOOL", set: null },
	"tls.client.certificate.is_unknown_ca": { get: "BOOL", set: null },
	"tls.client.certificate.is_verified": { get: "BOOL", set: null },
	"tls.client.certificate.issuer_dn": { get: "STRING", set: null },
	"tls.client.certificate.not_after": { get: "TIME", set: null },
	"tls.client.certificate.not_before": { get: "TIME", set: null },
	"tls.client.certificate.raw_certificate_b64": { get: "STRING", set: null },
	"tls.client.certificate.serial_number": { get: "STRING", set: null },
	"tls.client.cipher": { get: "STRING", set: null },
	"tls.client.ciphers_list": { get: "STRING", set: null },
	"tls.client.ciphers_list_sha": { get: "STRING", set: null },
	"tls.client.ciphers_list_txt": { get: "STRING", set: null },
	"tls.client.ciphers_sha": { get: "STRING", set: null },
	"tls.client.handshake_sent_bytes": { get: "INTEGER", set: null },
	"tls.client.iana_chosen_cipher_id": { get: "INTEGER", set: null },
	"tls.client.ja3_md5": { get: "STRING", set: null },
	"tls.client.ja4": { get: "STRING", set: null },
	"tls.client.protocol": { get: "STRING", set: null },
	"tls.client.servername": { get: "STRING", set: null },
	"tls.client.tlsexts_list": { get: "STRING", set: null },
	"tls.client.tlsexts_list_sha": { get: "STRING", set: null },
	"tls.client.tlsexts_list_txt": { get: "STRING", set: null },
	"tls.client.tlsexts_sha": { get: "STRING", set: null },
	"transport.bw_estimate": { get: "INTEGER", set: null },
	"transport.type": { get: "STRING", set: null },
	"waf.anomaly_score": { get: "INTEGER", set: "INTEGER" },
	"waf.blocked": { get: "BOOL", set: "BOOL" },
	"waf.counter": { get: "INTEGER", set: "INTEGER" },
	"waf.executed": { get: "BOOL", set: "BOOL" },
	"waf.failures": { get: "INTEGER", set: null },
	"waf.http_violation_score": { get: "INTEGER", set: "INTEGER" },
	"waf.inbound_anomaly_score": { get: "INTEGER", set: "INTEGER" },
	"waf.lfi_score": { get: "INTEGER", set: "INTEGER" },
	"waf.logdata": { get: "STRING", set: "STRING" },
	"waf.logged": { get: "BOOL", set: "BOOL" },
	"waf.message": { get: "STRING", set: "STRING" },
	"waf.passed": { get: "BOOL", set: "BOOL" },
	"waf.php_injection_score": { get: "INTEGER", set: "INTEGER" },
	"waf.rce_score": { get: "INTEGER", set: "INTEGER" },
	"waf.rfi_score": { get: "INTEGER", set: "INTEGER" },
	"waf.rule_id": { get: "INTEGER", set: "INTEGER" },
	"waf.session_fixation_score": { get: "INTEGER", set: "INTEGER" },
	"waf.severity": { get: "INTEGER", set: "INTEGER" },
	"waf.sql_injection_score": { get: "FLOAT", set: null },
	"waf.xss_score": { get: "STRING", set: "INTEGER" },
	"workspace.bytes_free": { get: "INTEGER", set: null },
	"workspace.bytes_total": { get: "INTEGER", set: null },
	"workspace.overflowed": { get: "BOOL", set: null },
};
